name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.SECRET }}
        TARGET_REPO: JunLiangWangX/HTML-Guide
        TARGET_BRANCH: deploy
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist
        
  push-deploy-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
          github_token: ${{ secrets.SECRET }}
          repository: JunLiangWangX/HTML-Guide 
          branch: deployServer
