name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.SECRET }}
        TARGET_REPO: JunLiangWangX/HTML-Guide
        TARGET_BRANCH: deploy
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist
        
        
        
  push-deploy-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Up merge
      uses: bambamboole/gha-upmerge@v1.0.1
      with:
        from_branch: master
        to_branch: develop
        push_token: ${{ secrets.SECRET }}
