name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: JunLiangWangX/HTML-Guide
        TARGET_BRANCH: docSite
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docSite/.vuepress/dist
