name: Deploy(domestic)
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Fetch resources
      run: ./deploy.sh
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: 12.x
    - run: npm i
    - run: npm run build --if-present
