name: Deploy(domestic)
on: [push,pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Fetch resources
      run: ./deploy.sh
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: 12.x
    - run: npm i
    - run: npm run build --if-present
    
    - name: deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.0 
      with:  
          username: 'root'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './docs/.vuepress/dist/*'  # 对应我们项目build的文件夹路径
          remote_path: '/home/www/htdocs/wangjunliang/HTML-Guide'
