name: Generate readme file
on: [push]
jobs:
  generate-readme-file:
    runs-on: ubuntu-latest
    steps:
     - name: Contributors and sponsors
       uses: lowlighter/metrics@latest
       with:
         filename: resource/repository.svg
         token: ${{ secrets.SECRET }}
         base: ""
         template: repository
         repo: HTML-Guide
         plugin_people: yes
         plugin_people_types: contributors, stargazers, watchers, sponsors

     - name: Detailed report
       uses: lowlighter/metrics@latest
       with:
         filename: resource/detailed.svg
         token: ${{ secrets.SECRET }}
         base: ""
         plugin_pagespeed: yes
         plugin_pagespeed_detailed: yes
         plugin_pagespeed_pwa: yes
         plugin_pagespeed_token: ${{ secrets.PAGESPEED }}
         plugin_pagespeed_url: https://junliangwangx.github.io/HTML-Guide/
         
     - name: Comment reactions
       uses: lowlighter/metrics@latest
       with:
         filename: resource/reactions.svg
         token: ${{ secrets.SECRET }}
         base: ""
         plugin_reactions: yes
         plugin_reactions_limit: 100
         plugin_reactions_details: percentage
